mongodb-operator is pushed
kubedb/schema-manager pull request #1
Opened 2021-11-29 10:25 UTC by ArnobKumarSaha

Mongo Operator is running successfully. User can be assigned to new Role on a mongo Database.

2021-11-29 10:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubedb/schema-manager?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubedb/schema-manager?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubedb/schema-manager?pullRequest=1) it.</sub>

2021-12-01 08:41 UTC, faem requested changes

2021-12-01 08:41 UTC, faem commented on controllers/schema/mongodbdatabase_controller.go
> +
Chekc MongoDB and Vault server is Ready before continue. Also watch for MongoDB and VaultServer, so that when they changes, database gets reconciled again.

2021-12-03 12:31 UTC, ArnobKumarSaha commented on controllers/schema/mongodbdatabase_controller.go
> +
All the problems has been resolved.

2021-12-10 17:58 UTC, faem requested changes

2021-12-13 04:36 UTC, ArnobKumarSaha commented on controllers/schema/mongodbdatabase_controller.go
> +	myFinalizerName := KubeDBSchemaManagerFinalizerName
Only the Group name ? Version is not required ?

2021-12-13 05:38 UTC, ArnobKumarSaha commented
all the requested changes are resolved.

2021-12-13 05:39 UTC, faem commented on controllers/schema/mongodbdatabase_controller.go
> +	myFinalizerName := KubeDBSchemaManagerFinalizerName
Only group

2021-12-15 09:32 UTC, faem requested changes

2021-12-15 09:32 UTC, faem commented on controllers/schema/mongodbdatabase_controller.go
> +			Name:      MongoRestoreSessionName,
generate from schema name

2021-12-15 09:32 UTC, faem commented on controllers/schema/mongodbdatabase_helper.go
> +package schema
move this file in `apis`.

2021-12-15 09:32 UTC, faem commented on controllers/schema/mongodbdatabase_helper.go
> +func getMongoAdminRoleName(dbName string) string {
Write all the below function as method of `MongoDBDatabase`

2021-12-17 04:44 UTC, ArnobKumarSaha commented on controllers/schema/mongodbdatabase_controller.go
> +	if fetchedSecretEngine.Status.Phase != SecretEnginePhaseSuccess || fetchedRole.Status.Phase != kvm_engine.RolePhaseSuccess {
SecretEnginePhase constants are declared in Vault operator deirectly. Can't import them.  source : sakib alamin vai

2022-01-07 10:08 UTC, faem commented on controllers/schema/mongodbdatabase_test.go
> +		to.CheckReadiness().Should(Succeed())
check them differently, not in the same function

2022-01-07 10:09 UTC, faem commented on controllers/schema/mongodbdatabase_test.go
> +		Expect(err).NotTo(HaveOccurred())
Do not run it from code, while running the test the operator should already be running externally.

2022-01-13 06:30 UTC, faem requested changes

2022-01-13 06:30 UTC, faem commented on controllers/schema/mongodbdatabase_controller.go
> +		Name:            obj.GetMongoInitContainerNameForPod(),
InitScriptContainerName

2022-01-13 06:30 UTC, faem commented on controllers/schema/mongodbdatabase_controller.go
> +	if vt == kutil.VerbCreated {
move it after error check

2022-01-13 06:30 UTC, faem commented on controllers/schema/mongodbdatabase_controller.go
> +	r.updateStatusForRepository(ctx, obj, fetcherdRepository.(*repository.Repository))
Only change conditions of MongoDBDatabase, no other objects. So remove the status change of other objects.

2022-01-13 11:47 UTC, ArnobKumarSaha commented on controllers/schema/mongodbdatabase_controller.go
> +	r.updateStatusForRepository(ctx, obj, fetcherdRepository.(*repository.Repository))
I am not updating the status of other objects.  This is 'for' not 'in'. updateStatusForRepository means updating status in MongoDBDatabase.Status which condition is associated with Repository.  Similiarly updateStatusForMongoDB means updating status in MongoDBDatabase.Status which condition is associated with MongoDB

2022-01-13 12:02 UTC, ArnobKumarSaha commented on controllers/schema/mongodbdatabase_controller.go
> +	}
this part is inside `else if obj.Spec.DeletionPolicy == smv1a1.DeletionPolicyDelete` block. No need to check here.  If DeletionPolicy DoNotDelete , then I have continued reconciliation `return true, nil`

2022-01-13 16:37 UTC, faem commented on controllers/schema/mongodbdatabase_controller.go
> +	}
I'm saying you should return error for DoNotDelete. Otherwise, the user won't know why delete is not working.

2022-01-13 16:38 UTC, faem commented on controllers/schema/mongodbdatabase_controller.go
> +	r.updateStatusForRepository(ctx, obj, fetcherdRepository.(*repository.Repository))
Okay

2022-02-09 06:23 UTC, faem requested changes

2022-02-09 06:23 UTC, faem commented on config/certmanager/certificate.yaml
> +# The following manifests contain a self-signed issuer CR and a certificate CR.
Add config directory in gitignore

2022-02-09 06:23 UTC, faem commented on controllers/schema/mongodbdatabase_controller.go
> +	err = r.runMongoSchema(ctx, mongo)
handle this error

2022-02-09 07:04 UTC, ArnobKumarSaha commented on controllers/schema/mongodbdatabase_controller.go
> +	err = r.runMongoSchema(ctx, mongo)
`err` of Line 102  is different from `err` of line 100 & 105.  if error occurs on runMongoSchema() , it is handled in line 105.  We can't handle error just after calling runMongoSchema() , because, I have to call updateSchemaStatus() just after it.  err/ nil doesn't matter. If I check error and return , conditions will not be updated properly.

2022-02-09 07:07 UTC, faem commented on controllers/schema/mongodbdatabase_controller.go
> +	err = r.runMongoSchema(ctx, mongo)
ok

2022-02-09 07:53 UTC, merged