Add stash support for mysqldatabase
kubedb/schema-manager pull request #19
Opened 2022-02-16 11:30 UTC by TasdidurRahman

Signed-off-by: TasdidurRahman <tasdid@appscode.com>

2022-02-16 13:40 UTC, spectro30 requested changes

2022-02-16 13:40 UTC, spectro30 commented on pkg/controllers/schema/mysqldatabase_controller.go
> +	//AppcatalogClient appcatCs.Interface
remove commented code if it's not required(for now or future)

2022-02-16 13:40 UTC, spectro30 commented on pkg/controllers/schema/mysqldatabase_controller.go
> +	if !kmapi.IsConditionTrue(schemaObj.Status.Conditions, string(schemaapi.DatabaseSchemaConditionTypeSecretAccessRequestReady)) {
why don't merge this if block with next one, as they are returning same things.

2022-02-16 13:40 UTC, spectro30 commented on pkg/controllers/schema/mysqldatabase_controller_helper.go
> +	//curCond := &schemaObj.Status.Conditions
remove?

2022-02-16 14:38 UTC, TasdidurRahman commented on pkg/controllers/schema/mysqldatabase_controller.go
> +	//AppcatalogClient appcatCs.Interface
done

2022-02-16 14:38 UTC, TasdidurRahman commented on pkg/controllers/schema/mysqldatabase_controller.go
> +	if !kmapi.IsConditionTrue(schemaObj.Status.Conditions, string(schemaapi.DatabaseSchemaConditionTypeSecretAccessRequestReady)) {
merged conditions

2022-02-17 10:20 UTC, spectro30 reviewed
LGTM

2022-02-18 04:12 UTC, merged