Add Support for MySQL
kubedb/schema-manager pull request #3
Opened 2021-12-14 08:50 UTC by TasdidurRahman

2021-12-14 08:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubedb/schema-manager?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubedb/schema-manager?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubedb/schema-manager?pullRequest=3) it.</sub>

2021-12-15 09:54 UTC, TasdidurRahman commented
Add Support for MySQL

2021-12-20 11:58 UTC, heheh13 commented on apis/schema/v1alpha1/mysqldatabase_types.go
> +	MySQLRef          kmodulesv1alpha1.AppReference `json:"my_sql_ref"`
Add comment before every field describing what's its doing.

2021-12-20 12:00 UTC, heheh13 commented on apis/schema/v1alpha1/mysqldatabase_types.go
> +	MySQLRef          kmodulesv1alpha1.AppReference `json:"my_sql_ref"`
like 
// MySQLRef is the reference to the origin database instance.

2021-12-20 12:09 UTC, heheh13 commented on controllers/schema/mysqldatabase_controller.go
> +	if schemaobj.Spec.Init.Script != (core.VolumeSource{}) && schemaobj.Spec.Init.Initialized != true {
https://github.com/kubedb/mysql/blob/master/pkg/controller/mysql.go#L112

2021-12-20 12:25 UTC, heheh13 commented on apis/schema/v1alpha1/mysqldatabase_types.go
> +	Init              Initer                        `json:"init,omitempty"`
I think `InitSpec` looks fine than Initer
seems like init spec should be optional. If it then add 
+optional
Init *InitSpec

2021-12-20 12:36 UTC, heheh13 commented on apis/schema/v1alpha1/mysqldatabase_types.go
> +	RepoRef           RestoreRef                    `json:"repo_ref,omitempty"`
seems another optional field.
```
+optional
Restore           RestoreConf                   `json:"restore,omitempty"`
```

2021-12-20 12:38 UTC, heheh13 commented on apis/schema/v1alpha1/mysqldatabase_types.go
> +type MySQLDatabasePhase string
Remove if not used.

2021-12-21 06:54 UTC, heheh13 requested changes
- fix typos
- remove unnecessary Comments
- use log instead print statements
- use camelCase
- recheck the function names. 
- run linter.`make fmt lint`

2021-12-21 06:54 UTC, heheh13 commented on controllers/schema/mysqldatabase_controller.go
> +				Kind: "MySQLRole",
use constant

2021-12-21 06:54 UTC, heheh13 commented on controllers/schema/mysqldatabase_controller.go
> +	curSecacreq, err := r.GetSecAccReqforSchema(ctx, schemaobj)
`curSecretAccessRequest`

2021-12-21 06:54 UTC, heheh13 commented on controllers/schema/mysqldatabase_controller.go
> +			// todo handle the case more precisely
.

2021-12-21 06:54 UTC, heheh13 commented on controllers/schema/mysqldatabase_controller.go
> +						Image:        "mysql:" + mysqlobj.Spec.Version, //"mysql:8.0.27",//getMysqlVersion(c, dbobj.Spec.MySQLRef),
get from mysqlverisons crd

2021-12-21 06:54 UTC, heheh13 commented on controllers/schema/mysqldatabase_controller.go
> +//trash :
Remove Trash :smile:

2021-12-21 06:54 UTC, heheh13 commented on controllers/schema/mysqldatabase_controller_helper.go
> +func CreateLocalRepo(r *MySQLDatabaseReconciler, schemaobj *schemav1a1.MySQLDatabase) (kutil.VerbType, error) {
`CreateLocalRepository`

2021-12-21 06:54 UTC, heheh13 commented on controllers/schema/mysqldatabase_controller_helper.go
> +func (r *MySQLDatabaseReconciler) GetSecAccReqforSchema(ctx context.Context, schemaobj *schemav1a1.MySQLDatabase) (*kvenginev1a1.SecretAccessRequest, error) {
.

2021-12-21 10:54 UTC, TasdidurRahman commented on apis/schema/v1alpha1/mysqldatabase_types.go
> +	MySQLRef          kmodulesv1alpha1.AppReference `json:"my_sql_ref"`
add descriptive comments 
change snake_case to camelCase

2021-12-21 10:55 UTC, TasdidurRahman commented on apis/schema/v1alpha1/mysqldatabase_types.go
> +	Init              Initer                        `json:"init,omitempty"`
change ```Init Initer``` to ```InitSpec *InitSpec```

2021-12-21 10:57 UTC, TasdidurRahman commented on apis/schema/v1alpha1/mysqldatabase_types.go
> +	RepoRef           RestoreRef                    `json:"repo_ref,omitempty"`
change ```RepoRef  RestoreRef ``` to ```Restore  *RestoreConf```

2021-12-21 10:58 UTC, TasdidurRahman commented on apis/schema/v1alpha1/mysqldatabase_types.go
> +	RepoRef           RestoreRef                    `json:"repo_ref,omitempty"`
add ```optional``` marker

2021-12-21 10:59 UTC, TasdidurRahman commented on apis/schema/v1alpha1/mysqldatabase_types.go
> +type MySQLDatabasePhase string
remove unused constants

2021-12-21 11:06 UTC, TasdidurRahman commented on controllers/schema/mysqldatabase_controller.go
> +	AppCatagolClient appcat_cs.Interface
fix typo

2021-12-21 11:07 UTC, TasdidurRahman commented on controllers/schema/mysqldatabase_controller.go
> +	//Recorder         record.EventRecorder
remove recorder

2021-12-21 11:07 UTC, TasdidurRahman commented on controllers/schema/mysqldatabase_controller.go
>  	// your logic here
remove comment

2021-12-21 11:08 UTC, TasdidurRahman commented on controllers/schema/mysqldatabase_controller.go
> +	//prepare finalizer to add later
remove comment

2021-12-21 11:10 UTC, TasdidurRahman commented on controllers/schema/mysqldatabase_controller.go
> +		_, _, errr := CreateOrPatchStatus(r.Client, &schemav1a1.MySQLDatabase{
change err to err2

2021-12-21 11:15 UTC, TasdidurRahman commented on controllers/schema/mysqldatabase_controller.go
> +				Kind: "MySQLRole",
create constant 
replace with constant

2021-12-21 11:16 UTC, TasdidurRahman commented on controllers/schema/mysqldatabase_controller.go
> +		//chech if the request is being approved
fix typo

2021-12-21 11:18 UTC, TasdidurRahman commented on controllers/schema/mysqldatabase_controller.go
> +	if schemaobj.Spec.Init.Script != (core.VolumeSource{}) && schemaobj.Spec.Init.Initialized != true {
change ```schemaobj.Spec.Init.Script != (core.VolumeSource{})``` to ```schemaobj.Spec.InitSpec != nil```

2021-12-21 11:22 UTC, TasdidurRahman commented on controllers/schema/mysqldatabase_controller.go
> +//trash :
remove trash

2022-02-09 12:24 UTC, TasdidurRahman commented
https://github.com/kubedb/schema-manager/pull/8

2022-02-09 12:24 UTC, closed without merging